🙈 Fixed small bugs

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -18,15 +18,15 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
-          node-version: '20'
+          node-version: "20"
 
       - name: Install Dependencies
         run: npm ci
 
       - name: Check Code Formatting with Prettier
         run: |
-          npm run prettier:check || { echo "Code is not formatted correctly. Please run 'npm run prettier:write' to fix the formatting issues."; exit 1; }
+          pnpm run prettier:check || { echo "Code is not formatted correctly. Please run 'pnpm run prettier:write' to fix the formatting issues."; exit 1; }
 
       - name: Lint Code with ESLint
         run: |
-          npm run lint || { echo "Linting failed. Please fix the linting issues according to the ESLint rules."; exit 1; }
+          pnpm run lint || { echo "Linting failed. Please fix the linting issues according to the ESLint rules."; exit 1; }
